### ISSUE TITLE
Elemental Unit Cards

### ISSUE THREAD

**Issue by NeonWolfe** [jdgwf/battletech-tools#13]
Would it be possible to pull up the 5-suit unit for Elementals instead of the 4-suit unit? Or be able to select 4, 5, or 6 suit squads of battle armor for the various factions?

**Comment by jdgwf** [comment]
I believe this is a MUL import issue. I'll see what I can do as I familiarize myself better with BA and Infantry specs

**Comment by jdgwf** [comment]
The MUL now has different squad sizes in the search results. Closing this as it fixes this issue 

from: http://www.masterunitlist.info/

> Battle Armor
> Monday, June 6, 2022
> 
> We have decided to bite the bullet and split squad size 4, 5, and 6 as separate units. This will allow the correct battle armor squad to be added to the force builder. Availability will be adjusted based on the squad size employed by a specific faction.
