### ISSUE TITLE
Minimal Damage Not Indicated

### ISSUE THREAD

**Issue by jlmorrison3** [jdgwf/battletech-tools#14]
Hello,

Love the site and so far has been working great for me. Last night I noticed that minimal damage indications where not present on a card I know has them. Specifically Flatbed Truck (SRM). On MUL is has an * next to medium and short range. Would it be possible to indicate this on when pulled into the alpha strike card on your tool?

**Comment by jdgwf** [comment]
Contacted SkyHigh @ the MUL. Those indicators are not being passed along n the data, but I'm sure he'll take care of it.

**Comment by jlmorrison3** [comment]
Awesome, thank you.
________________________________

**Comment by jdgwf** [comment]
Just an update - second email sent. Still waiting on any response. I hope he's okay.

**Comment by jdgwf** [comment]
This fix should be live! :)

**Comment by jlmorrison3** [comment]
Awesome, thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
