### ISSUE TITLE
UI Bug - Weapons and Equipment needs tabs or accordians

### ISSUE THREAD

**Issue by jdgwf** [jdgwf/battletech-tools#14]
Now that @Moonsword22  has started data entry for weapons and equipment, there's a definite need for the Step5 weapons UI to have tabs or accordians.

**Comment by Moonsword22** [comment]
I was just thinking about that at work earlier.  The easiest way to do it is probably on the equipment category, which needs a set of definitions somewhere.

Some sort of search functionality to find something specific might be useful, too, possibly with a simple delimiter to indicate multiple keywords:

- "Medium Laser" returns just the medium laser
- "Medium;Laser" returns any weapon with the strings "Medium" and "Laser" in its name, so it would pull in the ERML, MPL, MXPL, etc.

**Comment by jdgwf** [comment]
@Moonsword22 Don't forget to to perform a "pull" before you continue to work (and back up your current work just in case there's a nasty conflict if you're not familiar with resolving git conflicts ). I added a .sort field so that Small Medium and Large now sort right instead of pure alphabetical and lasers match up with lasers and ppcs match up with ppcs, etc :)

**Comment by jdgwf** [comment]
I think it's safe to leave that sort field as a non-local language field as it's basically grouping as they should be grouped, although a laser may come after a PPC in some languages #crossthatbridgewhenwegettoit

**Comment by Moonsword22** [comment]
The only thing I've done this week was the commit I pushed this morning, so no merge conflicts looming here.

**Comment by Moonsword22** [comment]
@jdwgf I may rearrange the sorting a little, it's a bit odd looking at it on my phone. Is there some guide to compiling the code?

**Comment by jdgwf** [comment]
I've added the .sort field since this morning :)

A grunt guide can be found here: http://gruntjs.com/getting-started

**Comment by Moonsword22** [comment]
Thanks.  It doesn't appear to have rebuilt but I've got Grunt installed along with the http-server plugin for NPM to use as a test environment.

**Comment by Moonsword22** [comment]
Ah-ha!  Got it compiled and now I can test changes.  Thanks for the link.
