### ISSUE TITLE
Alpha Strike Jump TMM Display Issues

### ISSUE THREAD

**Issue by einherjarvalk** [jdgwf/battletech-tools#15]
Continuing on from some troubleshooting that was discussed elsewhere and mostly resolved, TMM is currently not calculating correctly for units with an equal ground movement and jump movement distance. For units with identical ground and jump move distance, TMM is displayed as a single number that includes the +1 modifier for jump movement. However, the "normal" ground movement TMM is not displayed.

An example of an affected unit:

Shadow Hawk 5M
- Displayed TMM 3, MV 10"j
- MUL displays TMM 2, MV 10"j

This issue is not present on any unit that has separate ground and jump movement distances, including those with JMPW/JMPS special abilities. Some examples:

Grendel G: 
- Displayed TMM 3/4, MV 18"/14"j, no movement special abilities

Shadow Hawk 2H
- Displayed TMM 2/2, MV 10"/6"j, JMPW1

Phoenix Hawk 7K
- Displayed TMM 2/4, MV 12"/18"j, JMPS1

**Comment by jdgwf** [comment]
Sorry I didn't get the email notification for these last rounds of issues.

Thank you! This should be fixed the latest Commit
