### ISSUE TITLE
Unity availability incorrect?

### ISSUE THREAD

**Issue by creiht** [jdgwf/battletech-tools#16]
I was playing around with making a list, and found that one of my units wasn't showing as available.  After some experimentation, it would appear that the app is using the Production Era for availability, and I usually go by Availability Era from the MUL.  Would it be possible to go by availability era instead, or possibly have a toggle to choose which?

For reproduction, I was looking at the Kanga Hovertank in the Clan Invasion era.

Thanks!

**Comment by jdgwf** [comment]
Actually fixed in https://github.com/jdgwf/battletech-tools/commit/60f8c5161c719aae7839964296b31dbb6ce84310 :)

**Comment by creiht** [comment]
Dude, that's awesome, thanks!  This is a really cool tool, and really appreciate the work you are doing.
