### ISSUE TITLE
Ammunition and Items need Explosive tag

### ISSUE THREAD

**Issue by jdgwf** [jdgwf/battletech-tools#18]
For BattleValue calculations relating to #11, we're going to need an
.explosive = true,
or 
.explosive = 1,
property for those items that explode when hit such as missile ammo, gauss, etc.

It's just fine to leave out the property for those items that don't explode, I'll be checking for its existence before its value :)

Thanks!

**Comment by Moonsword22** [comment]
Fixed as of latest commit (just realized I forgot to put the issue number in the message, though...).

**Comment by jdgwf** [comment]
Ha! No worries. I miss it half the time because I forget the exact keyword or phrasing that GH uses :)

Thank you!
