### ISSUE TITLE
Printing Units take too much space

### ISSUE THREAD

**Issue by JacobWeber117** [jdgwf/battletech-tools#24]
So A few weeks ago I could get 6 units along with the formation info onto a single page and now it seems to cap out the units per page to 4. And it gets really weird with the pdf generating a third blank page for no reason.

**Comment by jdgwf** [comment]
I was afraid that somebody with younger, better eyes wouldn’t like that change. I’ll revert and make a burrow for larger printing for we old folks by the end of the day 😎

**Comment by jdgwf** [comment]
Once the github pages catch up, you should be good to go again :)
