### ISSUE TITLE
Heat Sink Type Definition

### ISSUE THREAD

**Issue by Moonsword22** [jdgwf/battletech-tools#24]
Heat sinks need a type definition file that should drive the dropdown in step 3 to tie into availability logic and deal with Clan vs. IS as well as Clan laser heat sinks.

**Comment by jdgwf** [comment]
I'll have to look up what the heck a laser heat sink is :)

**Comment by Moonsword22** [comment]
Basically Clan DHS but they slightly reduce the chance of an ammo explosion but it makes you easier to hit (and probably spot) in the dark if you're generating heat.

The real fun starts with prototype DHS, which are bolted on top of the engine's single heat sinks.  They're not widespread, with most designs I've heard of using them tied to the War of 3039 timeframe and a few in the Reunificaiton War or very late Age of War.
