### ISSUE TITLE
Ammo List Filter

### ISSUE THREAD

**Issue by Moonsword22** [jdgwf/battletech-tools#28]
The ammunition list probably needs to filter for the weapons actually on the unit in question to avoid being hopelessly bloated by all of the alternative ammunition types available.

By design, ammunition item tags contain the parent weapon's tag so the filtering should be straightforward logically.

**Comment by Moonsword22** [comment]
@jdgwf You mind taking a look at this?  The solution I came up with works in testing but it feels like a bit of a clumsy hack.

**Comment by jdgwf** [comment]
The logic looks fine, it may feel clunky, but it's less so than what I was targeting. We can easily optimize it later if speed becomes and issue ( I doubt it, it's quite readable now). You're using a esc6 for/let/of statement I wasn't aware of, and since we're targeting modern browsers this should be fine. I'm now wanting to go in and clean up all my standard for loops ;)

**Comment by Moonsword22** [comment]
Looking at that code again, it could stand some further refactoring, both for readability and maintainability.

`isAvailableAmmoType` is named inelegantly because it's being set to `true` on something that isn't ammo.  Functionally it's acting as both `isAvailableAmmoType` and `isNotAmmo` which is bound to confuse someone later.  (It just confused me and I wrote it yesterday!)

I probably need to refactor the equipment data with a `parent_weapon` tag for the ammunition and an `is_ammo` for everything rather than doing string searching on the fly.  Then I just check whether the parent weapon is in the equipment list and break out of the loop if it's located for efficiency.  There's also no reason to do the loop if we already know something should be included because it's not ammo.

**Comment by Moonsword22** [comment]
Note to self: Fix that `for` into an index loop on the array contents while you're refactoring.
