### ISSUE TITLE
TSM interaction with Heat

### ISSUE THREAD

**Issue by PhelanBoots** [jdgwf/battletech-tools#28]
Using the Alpha Strike tool, if I give a mech with TSM a level of heat it modifies the movement as if it didn’t have TSM.

Great work though, I use the app all the time!

**Comment by jdgwf** [comment]
> Using the Alpha Strike tool, if I give a mech with TSM a level of heat it modifies the movement as if it didn’t have TSM.
> 

Will look into this today
> 
> 
> Great work though, I use the app all the time!

Thanks! I wish I had more time 💙

**Comment by jdgwf** [comment]
@PhelanBoots try it now 🤨

**Comment by PhelanBoots** [comment]
> @PhelanBoots try it now 🤨

Working, thanks!
