### ISSUE TITLE
Issues adding mechs to Lance

### ISSUE THREAD

**Issue by FrankFromHR** [jdgwf/battletech-tools#29]
I’m unable to add mechs to the Lance groups, it gives me the option but when I select it I am taken to the display page for the data sheet instead of it being added to the Lance.

I’ve tried this on Chrome and Safari browsers and tried it on an iPad and iPhone, haven’t had a chance to try it on my Windows desktop yet.

**Comment by FrankFromHR** [comment]
I tested with a windows 10 desktop and I’m seeing the same behaviour.

**Comment by jdgwf** [comment]
I'd bet it's my fault. I made some big changes to simplify the conversion from the MUL, and thought I tested everything. 

I'm on it, Frank :)

**Comment by jdgwf** [comment]
Fixed and Patched. It'll take about 5 minutes for the GitHub pages to show up version 0.6.2 on the About page which fixes this.

Thanks you :)
