### ISSUE TITLE
Add Google Analytics to the application

### ISSUE THREAD

**Issue by darthmolen** [jdgwf/battletech-tools#30]
Tracking how the application is used can go a long ways towards making a better user experience.

**Comment by darthmolen** [comment]
http://angulartics.github.io/ One possible solution.

**Comment by jdgwf** [comment]
I'm all for an open solution too. I think it'd be interesting for all visitors to know who's coming from where and seeing what they're doing. I don't see this as needing to be a secret.

**Comment by jdgwf** [comment]
Verified. This is looking great.
