### ISSUE TITLE
Clean up for loops

### ISSUE THREAD

**Issue by jdgwf** [jdgwf/battletech-tools#33]
ECMAScript 6/ECMAScript 201 for-let-of loops aren't supported by ie11 (it works well with Edge, but not everyone runs Win10). Let's make sure that we use something compatible with that baseline, so that the app doesn't break :(

**Comment by Moonsword22** [comment]
That's what I get for not reading all the way through the MDN page on it.

**Comment by jdgwf** [comment]
I was wanting to make all the for loops that way. I loved it.
