### ISSUE TITLE
Pilot SPA bug

### ISSUE THREAD

**Issue by david-d-ellsworth** [jdgwf/battletech-tools#35]
Greetings, this is the first time I have used GitHub and so I hope I'm doing this correctly.

The bug, if you call it that, I found is that for Special Pilot Abilities (SPA), you can only add 1 SPA for your pilot.  As I understand it, a really advanced pilot could have up to 3 SPA with a total of no more than 6 points.  Unless I am missing it, I don't see how to add more than 1 SPA to any one pilot.  I hope that this is not a difficult error to correct.

Or if anyone knows how to add more than 1 SPA to a pilot, please let me know!

Thank you for this awesome program and I pray your health is improving.
David Ellsworth

**Comment by jdgwf** [comment]
This should be working for you now. Green or worse pilots won't get a drop-down, Regulars will get one, Elite or Vets will get 2 drop down, and those amazing Heroes and Legends will get 3
