### ISSUE TITLE
"Tablet View" for gameplay

### ISSUE THREAD

**Issue by WarWolfen** [jdgwf/battletech-tools#5]
The Alpha-Strike tool could offer an addition to the gameplay view. It could look like the card is full screen and with a navigation at the top for the units and on the left for the mechs (or units). In this way, it would be a charm to use the cards on a tablet standing next to the gaming table.

**Comment by jdgwf** [comment]
Can you make a more visual mock-up of what you’re describing? I’m about to reopen this project and rewrite likely using react & typescript. A lot of my problem with this project was “JavaScript fatigue.” I’d really like to continue work on it.

I’ve got a pretty big project I’m closing up in the next few months and this will be on full burn again. :)

**Comment by WarWolfen** [comment]
Hi! Nice to hear back from you! With this I mean something like in my own project:
![image](https://user-images.githubusercontent.com/16292643/61436078-47d74b80-a93a-11e9-98ac-dc17fe96ddc5.png)

You see the "tabs" at the top? So you can switch between mechs and there is no need to scroll up and down (which makes it a lot more convenient on tablets in my view).

**Comment by WarWolfen** [comment]
Oh, and my project is here btw:
https://github.com/ClanWolf/ASCard

**Comment by jdgwf** [comment]
Cool! I bet something like that can be implemented.Sorry I missed this issue... it must have slipped through. I've been working on this beast: https://savaged.us 94K lines of TS and TSX code
